export const NIC_FOUNDERS = [
    "Abdul-Azeez Kamaldeen Omotayo",
    "Abe Febishola Oluwabunmi",
    "Abe Oluwafisayo Temitayo",
    "Abe Oluwatosin Tolulope",
    "Adama Mansur-Harun",
    "Adefarasin Adeshola Ebunoluwa",
    "Adegbenga Omoniyi Omotade",
    "Adeniji Tolulope Elias",
    "Adeniyi Adebanjo Samuel",
    "Adeniyi Oghenetega Patience",
    "Adeoye Adetola Esther",
    "Adewale Adesoji Emmanuel",
    "Afe Alimot Ejide",
    "Agu Abel Chukwuka",
    "Aizebhughele Isibhakhomen John-Kelvin",
    "Ajayi Omowumi Abigail",
    "Ajayi Samuel Omotunde",
    "Ajibola Opeyemi Ayodeji",
    "Ajiboye Bola Taiye",
    "Akinsanmi Abosede Janet",
    "Alabi Temitope Opeyemi",
    "Aliu Deborah Ateso",
    "Amadi Gift Onyinyechi",
    "Amos Gbolaru",
    "Apeh Anthony Michael",
    "Apst. Onyema Favour Modestus",
    "Atunwa Olusola",
    "Awotunde Sunday Oluwole",
    "Babalola Olorunfemi",
    "Babarinde Farouk Olamide",
    "Babarinde Tajudeen Adebowale",
    "Bamidele Aderonke Cecilia",
    "Barr. Godwin Okuja",
    "Basuo Benjamin Ayebatonye",
    "Bonire Richard Olufemi",
    "Briona P. Gardner",
    "Bukola Bammeke",
    "Caleb Ikechukwu Ndubuisi",
    "Charles Abioro",
    "Cherish Ayomide Olutade",
    "Coker Abayomi Adegoke",
    "Coker Tolulope Wuraola",
    "Dada Abiodun",
    "Davies Oluwaseun Harrison",
    "Dominion Emoyoma Favour",
    "Dominion Oghenero Splendour",
    "Doris Ibhade Ibhawaegbele",
    "Dr Desmond Onyemechi Okocha",
    "Ebiware Nnebuogo Helen",
    "Efe Osagie",
    "Ejere Kenneth Imohimi",
    "Ejiogu Ngozi Joyce",
    "Elujoba Olaolu Femi",
    "Emmanuel Michael Elechi",
    "Emmanuel Olusoji Ogunmefun",
    "Emmanuel Oluwatosin Atoke",
    "Engr. Adewunmi Semiat Abiola",
    "Eniola Ajuwon",
    "Eseoghene Bose Ajayi",
    "Esther Temidunni Funmilayo",
    "Ezekiel C. Michael",
    "Fadlullah Olamilekan Harun",
    "Fafunwa Esseteru Agens",
    "Faith Azike",
    "Falowo-Asojo Ayobamidele",
    "Falowo-Asojo Deborah",
    "Fashina Salamat Abimbola",
    "Favour (May) Ifeanyichukwu Erunomase",
    "Favour Chioma Jack",
    "Florence Okegbe",
    "Funmi Lydia Olusan",
    "Gladys Olufunke Etim",
    "Glorious Amalu-Jack",
    "Hannatu John Ladong",
    "Henry Lopentz Umuai",
    "Ige Yinka Abraham",
    "Ighavongbe Adesuwa Vultina",
    "Ikeme Caroline Ngozi",
    "Iniobong Adaete",
    "Isaac O. Odetoyinbo",
    "Jerome Terpase Dooga",
    "John Samuel Onwukwe",
    "Joshua Ajayi",
    "Joy Akibu",
    "Joy Alexandria Ogbonna",
    "Joy Mark Oguche",
    "Jude Chibuike Kanu",
    "Justine Nwokoro",
    "Kayode-Koko Mariam O",
    "Makanjuola Victoria Temitope",
    "Maryann Achebe Samuel-Afele",
    "Millicent Oluwatosin Olusan",
    "Mohammed Kazeem Oladimeji",
    "Mohammed Mafeng Abdulsalam",
    "Mr Aigbe Samuel Tosin",
    "Mrs Alice Godwin",
    "Mrs. Ibeh Joy",
    "Musoe Osamu Joshua",
    "Nnamdi Obi Ikechukwu",
    "OLALEKAN OLUKAYODE ADENIJI",
    "Obadina Kazeem Olanrewaju",
    "Obott Nathaniel",
    "Odiatu Onyeka Elizabeth",
    "Odusi Oluwatosin Rebecca",
    "Ogbe Anyira",
    "Ogheneovo Elizabeth",
    "Oghoejuoma J.V Orodje",
    "Ogooluwa Temiloluwa Omotade",
    "Okoro Bernadine Evelyn",
    "Oladehinde Esther Bolaji",
    "Oladimeji Olufemi",
    "Oladimeji Olufolake M.",
    "Oladokun Bayonle Afeez",
    "Olaluwoye Mary Yemisi",
    "Olanrewaju Abraham O",
    "Olaopa Subuola Keren",
    "Olarewaju Eunice Aanu",
    "Olasubomi Olayinka Bali",
    "Olemba Jacinta Oluebube",
    "Olota Ayodeji Adesayo",
    "Olufunmilayo Olashubomi Ige",
    "Olutosin Olaitan Zibili",
    "Omatseye Daisy Aina",
    "Omofhemih Gloria Abiodun",
    "Omorogieva Aghama Friday",
    "Onuche-Thomas Hope Eloho",
    "Opeagbe Abiola Victoria",
    "Orire Memunat",
    "Osamadeko Ifeoluwa Blessing",
    "Ossai Ifeoma Roselyn",
    "Oyegoke Omoniyi Oladimeji",
    "Peace Oluchi Ada Onu",
    "Precious Ayobami Olutade",
    "Prince Kennedy Mark Oguche",
    "Princewill O. Akamo",
    "Prosper Uchenna Jack",
    "Revd Samuel Oluwagbemileke Idowu",
    "Salako Pauline Folashade",
    "Salako Toluwalope Olayinka",
    "Shomoye Anita Queen",
    "Shomoye Taiwo Shakur Adebowale",
    "Simon Gloria",
    "Sokoya Adebayo Adedoyin",
    "Sorinola Lawrence Olalekan",
    "Soyemi Esther Omotayo",
    "Stanley Fredricks Andrew",
    "Susan Temitayo Olusan",
    "TEMILOLA, Olusegun Moses",
    "Taiwo Olusumbo Ayomikun",
    "Taoheed Obadina",
    "Temilade Ajuwon",
    "Temitayo A. Adeniji",
    "Tomiwa Onasebu",
    "Topman Ibiang Francis",
    "Ukonu Emmanuel Ikechukwu",
    "Umaru Liman Abdullahi",
    "Umezi Victor Chinenye",
    "Victor Oluyemi Olusan",
    "Vivian Nwokoro"
];
