export const NIC_FOUNDERS = [
    "Adegbenga Omoniyi Omotade",
    "Awotunde Sunday Oluwole",
    "Aizebhughele Isibhakhomen John-Kelvin",
    "Stanley Fredricks Andrew",
    "Oladehinde Esther Bolaji",
    "Babarinde Tajudeen Adebowale",
    "Babarinde Farouk Olamide",
    "Orire Memunat Morenikeji",
    "Sokoya Adebayo Adedoyin",
    "Abe Oluwafisayo Temitayo",
    "Unohai Henry",
    "Coker Tolulope Wuraola",
    "Odiatu Onyeka Elizabeth",
    "Henry L. Umuai",
    "Ndubusi I Caleb",
    "Olaopa Subuola Keren",
    "Umezi Chinenye Victor",
    "Fashina Salamat Abimbola",
    "Hope Eloho Onuche-Thomas",
    "Babalola Olorunfemi",
    "Adewunmi Semiat Abiola",
    "Alabi Temitope Opeyemi",
    "Apeh Anthony Michael",
    "Adeniyi Oghenetega Patience",
    "Adama Mansur-Harun",
    "Obadina Kazeem Olanrewaju",
    "Umaru Liman Abdullahi",
    "Salako Pauline Folashade",
    "Harun Fadlullah Olamilekan",
    "Dada Abiodun Oladiran",
    "Omofhemih Gloria Abiodun",
    "Ajayi Omowumi Abigail",
    "Ajayi Samuel Omotunde",
    "Ighavongbe Adesuwa Vultina",
    "Janet Abosede Akinsanmi",
    "Okoro Bernadine Evelyn",
    "Bukola Bammeke",
    "Osamadeko Ifeoluwa Blessing",
    "Oluwatosin Rebecca Odusi",
    "Emmanuel Oluwatosin Atoke",
    "Simon Gloria Adeola",
    "Soyemi Esther Omotayo",
    "Gladys Olufunke Etim",
    "Nathaniel Obott",
    "Temilola Olusegun Moses",
    "Opeagbe Abiola Victoria",
    "Fafunwa Esseteru Agnes",
    "Ogooluwa TemilOluwa Omotade",
    "Victor Oluyemi Olusan",
    "Olanrewaju Abraham",
    "Ajayi Joshua",
    "Prince Kennedy Mark Oguche",
    "Joy Mark Oguche",
    "Elizabeth Ashake Kennedy-Oguche",
    "Peace Oluchi Ada Onu",
    "Esther Temidunni Funmilayo",
    "Ogbonna Joy Alexandria",
    "Topman Ibiang Francis",
    "Ibeh Joy Ebere",
    "Lkeme Caroline Ngozi",
    "Emmanuel Michael Elechi",
    "Afe Alimot Ejide",
    "John Samuel Onwukwe",
    "Makanjuola Victoria Temitope",
    "Jacinta Olemba",
    "Prosper Uchenna Jack",
    "Chioma Jack",
    "Oladimeji Olufolake Mubo",
    "Glorious Amalu-Jack",
    "Olarewaju Eunice Aanu",
    "Hannatu John Ladong",
    "Funmi Lydia Olusan",
    "Susan Temitayo Olusan",
    "Nnamdi Ikechukwu Obi",
    "Oladimeji Olufeimi S",
    "Agu Abel Chukwuka",
    "Favour Chioma Jack",
    "Precious Ayobami Olutade",
    "Mohammed Kazeem Oladimeji",
    "Kayode-Koko Mariam Oluwafemi",
    "Coker Adegoke",
    "Olasubomi Olayinka Bali",
    "Adeniyi Adebanjo Samuel",
    "Sorinola Lawrence Olalekan",
    "Adeniji Tolulope Elias",
    "Olalekan E. Adeniji",
    "Abioro Charles",
    "Zibili Olutosin Olaitan",
    "Ajiboye Bola Taiye",
    "Ige Olufunmilayo Olashubomi",
    "Salako Tuluwalope. Olayinka",
    "Davies Oluwaseun Harrison",
    "Ige Yinka A.",
    "Onasebu Tomiwa Dare",
    "Samuel Oluwagbemileke Idowu",
    "Taiwo Olusumbo Ayomikun",
    "Oladokun Bayonle Afeez",
    "Cherish Ayomide Olutade",
    "Adekola Mojisola Oluwayemisi",
    "Adekola Oluseyi Jonathan",
    "Joy Akibu",
    "Oyegoke Omoniyi Oladimeji",
    "Deborah Aliu Ateso",
    "Aigbe Samuel Tosin",
    "Shomoye Taiwo Shakur Adebowale",
    "Omatseye Daisy Aina",
    "Maryann Achebe Samuel -Afele",
    "Shomoye Anita Queen",
    "Eseoghene Bose Ajayi",
    "Onyema Favour Modestus",
    "Omorogieva Aghama Friday",
    "Musoe Osamu Joshua",
    "Doris Ibhade Ibhawaegbele",
    "Atunwa Olusola",
    "Falowo-Asojo Ayobamidele",
    "Falowo-Asojo Deborah",
    "Olaluwoye Mary Yemisi",
    "Abdul-Azeez Kamaldeen Omotayo",
    "Jude Chibuike Kanu",
    "Amadi Gift Onyinyechi",
    "Princewill O. Akamo",
    "Ossai Ifeoma Rosslyn",
    "Oghoejuoma James-Vote Orodje",
    "Mbadugha Blessing Anyira",
    "Dominion Oghenero Splendour",
    "Dominion Emoyoma Favour",
    "Ajibola Opeyemi Ayodeji",
    "Iniobong Adaete",
    "Ejiogu Ngozi Joyce",
    "Favour Ifeanyichukwu Erunomase",
    "Briona Gardner",
    "Temitayo A. Adenij",
    "Obadina Taoheed Olaide",
    "Temilade E. A. Ajuwon",
    "Eniola Ajuwon",
    "Isaac O. Odetoyinbo",
    "Emmanuel Olusoji Ogunmefun",
    "Amos Gbolaru",
    "Ogheneovo Elizabeth"
];
