ALTER TABLE memberships 
ADD COLUMN IF NOT EXISTS paid_recapitalization BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS recapitalization_amount DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_payment_reference TEXT,
ADD COLUMN IF NOT EXISTS last_payment_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS is_founding BOOLEAN DEFAULT FALSE;
